// <auto-generated />
using DGII.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DGII.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616132922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DGII.Domain.Entities.ComprobanteFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("itbis18");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("ncf");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("rnc_cedula");

                    b.HasKey("Id");

                    b.HasIndex("NCF")
                        .IsUnique();

                    b.HasIndex("RncCedula");

                    b.ToTable("comprobantes_fiscales", (string)null);
                });

            modelBuilder.Entity("DGII.Domain.Entities.Contribuyente", b =>
                {
                    b.Property<string>("RncCedula")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("rnc_cedula");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.HasKey("RncCedula");

                    b.ToTable("contribuyentes", (string)null);
                });

            modelBuilder.Entity("DGII.Domain.Entities.ComprobanteFiscal", b =>
                {
                    b.HasOne("DGII.Domain.Entities.Contribuyente", null)
                        .WithMany()
                        .HasForeignKey("RncCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
